# Generated by Django 3.1.7 on 2021-02-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
    ]
